### ISSUE TITLE
Mutating Sorbet T nodes even with ignore patterns

### ISSUE THREAD

**Issue by dkubb** [mbj/mutant#1408]
I have a configuration like this:

```yaml
---
integration:
  name: minitest
requires:
  - boa
includes:
  - test
mutation:
  ignore_patterns:
    - send{receiver=const{name=T}}
    - send{receiver=send{receiver=const{name=T}}}
  operators: full
matcher:
  subjects:
    - Boa*
```

But I am still seeing mutations like this:

```
-----------------------
Killfork: #<Process::Status: pid 24704 exit 0>
Log messages (combined stderr and stdout):
[killfork] Run options: 
[killfork] 
[killfork] # Running:
[killfork] 
[killfork] 
[killfork] 
[killfork] Finished in 0.001562s, 640.2051 runs/s, 640.2051 assertions/s.
[killfork] 
[killfork] 1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
@@ -1,4 +1,4 @@
 def min_length
-  T.must(length.begin)
+  length.begin
 end
```

Here is [a link to a recent build](https://github.com/dkubb/boa/actions/runs/7055425253/job/19205823551) that shows the results of a mutant run.

I suppose it's possible the ignore patterns are invalid, but they appear to work when I run the util, eg:

```bash
bundle exec mutant util mutation -e 'T.must(length.begin)' --ignore-pattern 'send{receiver=const{name=T}}' --ignore-pattern 'send{receiver=send{receiver=const{name=T}}}'
<cli-source>
```

I did notice that when mutant output's it's "environment" at the start it doesn't mention the ignore patterns. I don't know if they just haven't been added there, but perhaps they aren't being loaded into the runtime environment?
